# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'pathname'

fastlane_version "2.179.0"
default_platform :android

# Utils
import("src/utils.rb")

# PLATAFORM ANDROID
import("src/android.rb")

# PLATAFORM IOS
import("src/ios.rb")